[package]
name = "mini-v8"
version = "0.1.0"
authors = ["Skyler Lipthay <sl@skylerlipthay.com>"]
edition = "2018"
license = "MIT"

[dev-dependencies]
ansi_term = "0.12"
rustyline = "5.0"

[build-dependencies]
cc = "1.0"
